# Generated by Django 4.2.1 on 2023-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud1', '0002_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
